### ISSUE TITLE
Introduce logger and log levels like cloud SDK

### ISSUE THREAD

**Issue by avorima** [ionos-cloud/sdk-go-auth#2]
Using both sdk-go and sdk-go-auth is kind of awkward right now, because one allows to configure a logger and log levels and the other still uses stdlog and "debug".

Please implement https://github.com/ionos-cloud/sdk-go/issues/24 for this SDK.

**Comment by cristiGuranIonos** [comment]
should be fixed in [1.0.5](https://github.com/ionos-cloud/sdk-go-auth/releases/tag/v1.0.5)

**Comment by avorima** [comment]
Thanks!
