### ISSUE TITLE
Empty DefaultIonosBasePath breaks client from env

### ISSUE THREAD

**Issue by avorima** [ionos-cloud/sdk-go-auth#5]
## Description

Prior to https://github.com/ionos-cloud/sdk-go-auth/commit/dcf634aaef367aecc86cb3d824b7581a5d598c03#diff-bbc90acc33d891618fa383ec79747d6e8b4fc5ed3cf3aaa530c615fdb8efde90 it was possible to construct a client using the environment variable `IONOS_API_URL=https://api.ionos.com`.

The [same variable in sdk-go](https://github.com/ionos-cloud/sdk-go/blob/v6.2.1/configuration.go#L33) has the correct value for its context, but here it's missing `/auth/v1`.

## Expected behavior

Using `IONOS_API_URL=https://api.ionos.com` for all SDK's works.

## Environment

GO version: 
```
```
SDK version:
```
```
OS: 
```
```

**Comment by avirtopeanu-ionos** [comment]
Hi, I'll fix this, looks like an issue with direct indexing for that field in our mustache parser

**Comment by avirtopeanu-ionos** [comment]
Hi, this should be fixed in v1.0.10!
